### PR TITLE
Edit comments, Correct bool value in SeedClient data

### PR DESCRIPTION
**Pull request by awgregory**
Small change to seed client data file

### CODE REVIEW

**Comment by awgregory** [comment]
@KateYou please merge

**Comment by awgregory** [comment]
Going to go ahead and merge my own pull request to expedite getting change to seedClient data into develop

**Comment by jebert142** [comment]
Looks good Adrian, I don't see anything in the 3 files that you changed that would do harm to dev 👍

**Comment by awgregory** [comment]
Okay thanks Jon

**Pull request merged**
